kind: wasmer.io/App.v0
name: amrtm-app
owner: hishamkassi
package: php/php
env:
  APP_NAME: Amrtm
  APP_ENV: production
  APP_DEBUG: 'false'
  APP_URL: https://amrtm-app.wasmer.app
  LOG_CHANNEL: stderr
  DB_CONNECTION: mysql
  DB_HOST: db65613.databaseasp.net
  DB_PORT: '3306'
  DB_DATABASE: db65613
  DB_USERNAME: db65613
  DB_PASSWORD: 4d?NrK5+2#Pp
volumes:
- name: storage
  mount: /app/storage
scaling:
  mode: single_concurrency
app_id: da_RjPIgtQU1MBm
